# Generated by Django 3.2.8 on 2022-06-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('page', '0007_auto_20220627_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('redirect_to', models.URLField(help_text='The URL to redirect to')),
            ],
            options={
                'verbose_name': 'Redirector',
            },
            bases=('wagtailcore.page',),
        ),
    ]
