# Generated by Django 3.2.8 on 2022-07-07 19:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0003_homepagefeatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagefeatures',
            name='aspen_collection_spotlight_iframe',
        ),
        migrations.AddField(
            model_name='homepagefeatures',
            name='home_page_feature_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Link to a document instead of a page or external url. This will only work if no internal page, or external link is selected'),
        ),
        migrations.AddField(
            model_name='homepagefeatures',
            name='home_page_feature_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepagefeatures',
            name='home_page_feature_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepagefeatures',
            name='home_page_feature_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Overrides the title of the page'),
        ),
        migrations.CreateModel(
            name='HomePageAspenCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('aspen_collection_spotlight_iframe', models.CharField(blank=True, help_text='see https://search.pentictonlibrary.ca/Admin/CollectionSpotlights for collection spotlight iframe tags', max_length=300, null=True)),
                ('aspen_carousels', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspen_carousel', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
