# Generated by Django 3.1.7 on 2021-03-30 23:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import header_footer.models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('enable_alert', models.BooleanField(default=False)),
                ('alert_date', models.DateTimeField(default=datetime.datetime.now)),
                ('alert_text', wagtail.core.fields.RichTextField(blank=True)),
                ('alert_colour', models.CharField(choices=[('R', 'Red'), ('G', 'Green')], default='G', max_length=1)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_col', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='heading'))], classname='full title')), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('telephone', wagtail.core.blocks.StructBlock([('telephone', wagtail.core.blocks.CharBlock(form_classname='telephone'))])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('email', wagtail.core.blocks.StructBlock([('email', wagtail.core.blocks.EmailBlock(form_classname='email'))])), ('business_hours', header_footer.models.BusinessHourBlock())], blank=True)),
            ],
            options={
                'verbose_name': 'First Footer Column',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
