# Generated by Django 3.2.8 on 2022-05-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0002_formpage_thank_you_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='submit_button_text',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
