# Generated by Django 3.2.8 on 2022-07-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_resource', '0002_onlineresourcepage_resource_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineresourcepage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
